return {
  'user.deno',
  'user.run_script',
  'user.docker-compose',
  'user.tsc_build',
  'user.go',
  'user.git',
  'user.lua',
  'user.python',
  'user.node',
  'user.java',
  'user.runner',
  'user.logs',
  'user.fullstack',
  'user.kubectl',
  'user.nx',
}
