return {
  {
    'm4xshen/smartcolumn.nvim',
    opts = {
      colorcolumn = { '100', '120' },
      disabled_filetypes = {
        'alpha',
        'NvimTree',
        'Outline',
        'Trouble',
        'dap-repl',
        'dap-terminal',
        'dapui_breakpoints',
        'dapui_console',
        'dapui_scopes',
        'dapui_stacks',
        'dapui_watches',
        'dashboard',
        'help',
        'lazy',
        'lir',
        'markdown',
        'mason',
        'neo-tree',
        'neogitstatus',
        'oil',
        'packer',
        'spectre_panel',
        'startify',
        'startup',
        'toggleterm',
        'Lazy',
        'NvimTree',
        'help',
        'html',
        'markdown',
        'mason',
        'netrw',
        'tex',
        'text',
      },
      scope = 'window',
    },
  },
}
