return {
  -- {
  --   'ravitemer/mcphub.nvim',
  --   branch = 'main',
  --   keys = {
  --     { '<leader>$', '<Cmd>MCPHub<CR>', desc = 'Open MCB Hub' },
  --   },
  --   cmd = { 'MCPHub' },
  --   build = 'pnpm install -g mcp-hub@latest',
  --   -- build = 'bundled_build.lua',
  --   opts = function()
  --     return {
  --       -- use_bundled_binary = true,
  --       auto_toggle_mcp_servers = false,
  --       global_env = {
  --         GITHUB_PERSONAL_ACCESS_TOKEN = os.getenv('GITHUB_PERSONAL_ACCESS_TOKEN'),
  --         SLACK_USER_TOKEN = os.getenv('SLACK_USER_TOKEN'),
  --         SLACK_CLIENT_ID = os.getenv('SLACK_CLIENT_ID'),
  --         SLACK_CLIENT_SECRET = os.getenv('SLACK_CLIENT_SECRET'),
  --       },
  --       ui = {
  --         window = {
  --           border = vim.g.borderStyle,
  --           width = 0.9,
  --           height = 0.9,
  --         },
  --         wo = {
  --           winblend = vim.o.winblend,
  --           winhl = 'MCPHubMuted:Normal',
  --         },
  --       },
  --     }
  --   end,
  -- },
}
