return {
  -- {
  --   'lewis6991/hover.nvim',
  --   enabled = false,
  --   opts = {
  --     preview_opts = { border = 'rounded' },
  --     preview_window = false,
  --     title = true,
  --     mouse_providers = { 'LSP' },
  --     mouse_delay = 1000,
  --     init = function()
  --       require('hover.providers.lsp')
  --       require('hover.providers.man')
  --       require('hover.providers.dap')
  --       require('hover.providers.diagnostic')
  --
  --       local peek_supported_capabilities = {
  --         vim.lsp.protocol.Methods.textDocument_implementation,
  --         vim.lsp.protocol.Methods.textDocument_definition,
  --       }
  --       require('hover').register({
  --         name = 'LSP Peek',
  --         enabled = function(bufnr)
  --           return vim.iter(vim.lsp.get_clients({ bufnr = bufnr })):any(
  --             ---@param cli vim.lsp.Client
  --             function(cli)
  --               return vim.iter(peek_supported_capabilities):any(function(method)
  --                 return cli:supports_method(method, bufnr)
  --               end)
  --             end
  --           )
  --         end,
  --         execute = function(opts, done)
  --           local finished = false
  --           for _, method in ipairs(peek_supported_capabilities) do
  --             if
  --               vim.iter(vim.lsp.get_clients({ bufnr = opts.bufnr })):any(
  --                 ---@param cli vim.lsp.Client
  --                 function(cli)
  --                   return cli:supports_method(method, opts.bufnr)
  --                 end
  --               )
  --             then
  --               vim.lsp.buf_request(opts.bufnr, method, function(client, _bufnr)
  --                 return vim.lsp.util.make_position_params(0, client.offset_encoding)
  --               end, function(err, result, context, config)
  --                 if result == nil or vim.tbl_isempty(result) then
  --                   if not finished then
  --                     finished = true
  --                     return pcall(done, false)
  --                   else
  --                     return
  --                   end
  --                 end
  --                 local loc = result
  --                 if vim.islist(result) then
  --                   loc = result[1]
  --                 end
  --                 loc.uri = loc.uri or loc.targetUri
  --                 loc.range = loc.range or loc.targetRange
  --                 if loc.uri == nil or loc.range == nil then
  --                   if not finished then
  --                     finished = true
  --                     return pcall(done, false)
  --                   else
  --                     return
  --                   end
  --                 end
  --                 local _bufnr = vim.uri_to_bufnr(loc.uri)
  --                 vim.fn.bufload(_bufnr)
  --                 local range = loc.range
  --                 local ft = vim.bo[_bufnr].filetype
  --                 vim.treesitter.start(_bufnr, ft)
  --
  --                 local md_lines = {
  --                   '```' .. ft,
  --                   string.format(vim.bo[_bufnr].commentstring, method),
  --                 }
  --                 vim.list_extend(
  --                   md_lines,
  --                   vim.api.nvim_buf_get_lines(
  --                     _bufnr,
  --                     range.start.line,
  --                     range.start.line + math.ceil(vim.api.nvim_win_get_height(0) * 0.2),
  --                     false
  --                   )
  --                 )
  --                 table.insert(md_lines, '```')
  --                 if not finished then
  --                   finished = true
  --                   return pcall(done, {
  --                     lines = md_lines,
  --                     filetype = 'markdown',
  --                   })
  --                 else
  --                   return
  --                 end
  --               end)
  --               return
  --             end
  --           end
  --         end,
  --       })
  --     end,
  --   },
  --   keys = {
  --     {
  --       'K',
  --       function()
  --         require('hover').hover()
  --       end,
  --       desc = 'Hover',
  --     },
  --     {
  --       'gk',
  --       function()
  --         require('hover').hover_select()
  --       end,
  --       desc = 'Hover Select',
  --     },
  --     {
  --       '[h',
  --       function()
  --         require('hover').hover_switch('previous')
  --       end,
  --       desc = 'Previous hover provider.',
  --       mode = 'n',
  --       noremap = true,
  --     },
  --     {
  --       ']h',
  --       function()
  --         require('hover').hover_switch('next')
  --       end,
  --       desc = 'Next hover provider.',
  --       mode = 'n',
  --       noremap = true,
  --     },
  --   },
  -- },
}
